# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sketchConstraints.xdc

# IP: ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet
